# ------------------------------------------------
# [ ALACRITTY ]
# ------------------------------------------------

# ------------------------------------------------
# [ WINDOW ]
# ------------------------------------------------
window:
    padding:
        x: 5
        y: 5

    # Spread additional padding evenly around the terminal content.
    dynamic_padding: true

    # Allow terminal applications to change Alacritty's window title.
    dynamic_title: true

# ------------------------------------------------
# [ FONT ]
# ------------------------------------------------
font:
    normal:
        family: JetBrainsMono Nerd Font
        style: Regular

    bold:
        family: JetBrainsMono Nerd Font
        style: Bold

    italic:
        family: JetBrainsMono Nerd Font
        style: Italic

    bold_italic:
        family: JetBrainsMono Nerd Font
        style: Bold Italic

    # Point size
    size: 13

# If `true`, bold text is drawn using the bright color variants.
# draw_bold_text_with_bright_colors: false

# ------------------------------------------------
# [ COLORS ]
# ------------------------------------------------
import:
    - ~/.config/alacritty/themes/argi.yml
    # - ~/.config/alacritty/themes/kosmikoa.yml

# ------------------------------------------------
# [ MOUSE ]
# ------------------------------------------------
mouse:
    # If this is `true`, the cursor is temporarily hidden when typing.
    hide_when_typing: true
