# Configuration for Alacritty, the GPU enhanced terminal emulator.

# [ Window ]
window:
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
   x: 5
   y: 5

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true

  # Allow terminal applications to change Alacritty's window title.
  dynamic_title: true


# [ Font ]
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  # Point size
  size: 13

# If `true`, bold text is drawn using the bright color variants.
# draw_bold_text_with_bright_colors: false


# [ Colors ]
import:
  - ~/.config/alacritty/themes/kosmikoa.yml


# [ Mouse ]
mouse:
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

