[[columns]]
kind = "Pid"
style = "White|Black"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "User"
style = "White|Black"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Separator"
style = "White|BrightBlack"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "UsageCpu"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "UsageMem"
style = "ByPercentage"
numeric_search = false
nonnumeric_search = false
align = "Right"

[[columns]]
kind = "CpuTime"
style = "Yellow|Yellow"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "VmPeak"
style = "White|Black"
numeric_search = false
nonnumeric_search = false
align = "Center"

[[columns]]
kind = "Separator"
style = "White|BrightBlack"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "StartTime"
style = "BrightWhite|Black"
numeric_search = false
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "Command"
style = "Magenta|Magenta"
numeric_search = false
nonnumeric_search = true
align = "Left"
max_width = 80

[style]
header = "White|Black"
unit = "White|Black"
tree = "White|Black"

[style.by_percentage]
color_000 = "Blue|Blue"
color_025 = "Green|Green"
color_050 = "Yellow|Yellow"
color_075 = "Red|Red"
color_100 = "Red|Red"

[style.by_state]
color_d = "Red|Red"
color_r = "Green|Green"
color_s = "Blue|Blue"
color_t = "Cyan|Cyan"
color_z = "Magenta|Magenta"
color_x = "Magenta|Magenta"
color_k = "Yellow|Yellow"
color_w = "Yellow|Yellow"
color_p = "Yellow|Yellow"

[style.by_unit]
color_k = "Blue|Blue"
color_m = "Green|Green"
color_g = "Yellow|Yellow"
color_t = "Red|Red"
color_p = "Red|Red"
color_x = "Blue|Blue"

[search]
numeric_search = "Exact"
nonnumeric_search = "Partial"
logic = "And"

[display]
show_self = false
cut_to_terminal = true
cut_to_pager = false
cut_to_pipe = false
color_mode = "Auto"
separator = "│"
ascending = "▲"
descending = "▼"
tree_symbols = ["│", "─", "┬", "├", "└"]
abbr_sid = true

[sort]
column = 0
order = "Ascending"

[docker]
path = "unix:///var/run/docker.sock"

[pager]
mode = "Auto"
detect_width = true

