#!/usr/bin/env bash
#
# [ ALIASES ]


# [ Pacman ]
alias upgrade='sudo pacman -Syu'
alias pac='sudo pacman'
alias orph='pacman -Qtdq'
alias spkg='pacman -Q | rg'
alias ipkg='pacman -Qi'

alias findpac='fd ".+\.pac(new|save)" /etc 2>/dev/null'

# [ Paru ]
alias pdel='paru -Rsn'
alias delorph='paru -Qtdq | paru -Rns -'

# [ Exa ]
alias exa='exa --group-directories-first --icons'
alias ea='exa -lah --group-directories-first --git --icons'
alias et='exa -lah -TL2 --group-directories-first --git --icons'

# [ Git ]
alias gc='git clone'
alias gcm='git commit -m'
alias gs='git switch'
alias gpo='git pull origin'

# [ Neovim ]
alias sedit='sudo -E "${EDITOR:-nvim}"'
alias enote='cd "$XDG_DATA_HOME"/notes && nvim'
alias qnote='nvim "$XDG_DATA_HOME"/notes/quick.md'
alias e='nvim "$@"'

# [ Nnn ]
alias N='sudo -E nnn -e'

# [ Trash-cli ]
alias del='trash-put'
alias restore='trash-restore'

# [ Lang ]
alias z7='zig-0.7.1v'

# [ Files ]
alias ls='ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll='ls -l --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias la='ls -la --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias grep='grep --color=always -d skip'
alias cp='cp -i'
alias df='df -h'
alias free='free -m'
alias cmx='chmod 774'
alias perm='stat -c "%A %a %n"'

# [ Misc ]
alias :q='exit'
alias sc='systemctl'
alias Xress='xrdb "$XDG_CONFIG_HOME"/X11/xresources'
alias wname='xprop | grep WM_CLASS'
alias wget='wget --hsts-file="$XDG_CACHE_HOME"/wget-hsts'
alias awesometest='Xephyr :5 & sleep 1 ; DISPLAY=:5 awesome'
alias mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'
alias rgi='rg --no-ignore'
alias weechat='weechat -d "$XDG_CONFIG_HOME"/weechat'
alias cargou='cargo-install-update install-update'

