# [ local/share ]
- link:
    ~/.local/share/applications: local/share/applications
    ~/.local/share/fonts: local/share/fonts
    ~/.local/share/gnupg/gpg-agent.conf: local/share/gnupg/gpg-agent.conf

- create:
    - ~/.private
