# [ Sysytem ]
#
# use: `./install-standalone system-sudo`

- link:
  # /etc
    /etc/dracut.conf.d: system/etc/dracut.conf.d
    /etc/sv/snooze-fstrim: system/etc/sv/snooze-fstrim
    /etc/atool.conf: system/etc/atool.conf
    /etc/chrony.conf: system/etc/chrony.conf
    /etc/iwd: system/etc/iwd
    /etc/xbps.d: system/etc/xbps.d

