# [ ARGI ]
colors:
  primary:
    background: '0xf9f9fa'
    foreground: '0x202325'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  # Normal colors
  normal:
    black:   '0xcdd4d8'
    red:     '0x9e2f59'
    green:   '0x2e3f9f'
    yellow:  '0x202325'
    blue:    '0x202325'
    magenta: '0x202325'
    cyan:    '0x202325'
    white:   '0x202325'

  # Bright colors
  bright:
    black:   '0xcdd4d8'
    red:     '0x9e2f59'
    green:   '0x2e3f9f'
    yellow:  '0x202325'
    blue:    '0x202325'
    magenta: '0x202325'
    cyan:    '0x202325'
    white:   '0x202325'

