# ------------------------------------------------
# [ KOSMIKOA ]
# ------------------------------------------------

colors:
    primary:
        background: "0x23222b"
        foreground: "0xeae9ee"
    cursor:
        text: CellBackground
        cursor: CellForeground
    vi_mode_cursor:
        text: CellBackground
        cursor: CellForeground

    # Normal colors
    normal:
        black: "0x474557"
        red: "0xfc65b0"
        green: "0x62e89e"
        yellow: "0xe8ec77"
        blue: "0x57bbf4"
        magenta: "0xbe8fde"
        cyan: "0x00cfd0"
        white: "0xeae9ee"

    # Bright colors
    bright:
        black: "0x59566d"
        red: "0xfc65b0"
        green: "0x62e89e"
        yellow: "0xe8ec77"
        blue: "0x57bbf4"
        magenta: "0xbe8fde"
        cyan: "0x00cfd0"
        white: "0xeae9ee"
