#!/usr/bin/env zsh

# Open images with sxiv or imv
#   - Dependencies: fzf, fd, sxiv/imv

fimg () {
    local files

    if (( $+commands[imv] )); then
        IFS=$'\n' files=($(fd -p -e jpg -e png ~ | fzf --query="$1" --multi --select-1 --exit-0))
        [[ -n "$files" ]] && imv "${files[@]}"
    elif (( $+commands[sxiv] )); then
        IFS=$'\n' files=($(fd -p -e jpg -e png ~ | fzf --query="$1" --multi --select-1 --exit-0))
        [[ -n "$files" ]] && sxiv "${files[@]}"
    else
        echo "You need Sxiv or Imv"
        exit 1
    fi
}
