# ------------------------------------------------
# argi - vivid
# Author: novakane <mail@novakane.xyz>
# ------------------------------------------------

colors:
    light00: "f9f9fa"
    light01: "dce1e4"
    light02: "cdd4d8"

    dark00: "202325"
    dark01: "3a4043"
    dark02: "646e73"

    blue: "2e3f9f"
    red: "9e2f59"
    purple: "6b2e9f"

    err: "9f2e2f"
    warn: "9f5a2e"
    success: "577433"

    comment: "29748a"
    string: "254550"

    hblue: "dbf1fd"
    hyellow: "faefb1"
    hred: "fde7f6"
    hgreen: "c0fbd5"

core:
    regular_file: {}

    directory:
        font-style: bold

    executable_file:
        foreground: red
        font-style: bold

    symlink:
        font-style: italic
        foreground: dark01

    broken_symlink:
        foreground: dark02
        background: light01
    missing_symlink_target:
        foreground: dark02
        background: light01

    fifo:
        background: hblue

    socket:
        background: hred

    character_device:
        background: hgreen

    block_device:
        background: light01

    normal_text: {}

    sticky: {}

    sticky_other_writable: {}

    other_writable: {}

text:
    special:
        background: hyellow

    todo:
        font-style: bold

    licenses: {}

    configuration:
        foreground: purple

    other: {}

markup:
    font-style: italic

programming:
    source:
        background: hblue

    tooling:
        background: hblue

        continuous-integration:
            background: hblue

media:
    foreground: blue

office:
    foreground: blue

archives:
    foreground: purple
    font-style: underline

executable:
    font-style: bold

unimportant:
    foreground: dark01
