---
# [ YAMBAR ]

# [ Variables ]
base00: &base00 232227ff
base01: &base01 38383cff
base02: &base02 4e4e52ff
base03: &base03 6b5c7cff
base04: &base04 837593ff
base05: &base05 9d8fa9ff
base06: &base06 b7acbfff
base07: &base07 d2ccd6ff

red: &red f63d81ff
pink: &pink fc65b0ff
orange: &orange f5939cff
yellow: &yellow e8ec77ff
green: &green 2dcbb0ff
blue: &blue 57bbf4ff
magenta: &magenta a89beeff
cyan: &cyan 4db9c8ff

myfont: &myfont Overpass:style=Regular:pixelsize=16
sfont: &sfont Overpass:style=Regular:pixelsize=12

separator: &separator
  text: 
  font: *sfont
  foreground: *base02

# [ Bar ]
bar:
  height: 28
  location: top
  spacing: 5

  # Default
  font: *myfont
  foreground: *base07
  background: *base00
  border:
    width: 0

  # [ Left ]
  left:
    - label:
        content:
          list:
            spacing: 5
            items:
              - string:
                  text: 襤
                  font: *sfont
                  foreground: *cyan
                  left-margin: 10
                  on-click: /usr/bin/bash -c "wlogout"
              - string: {<<: *separator}
              - string:
                  text: 
                  font: *sfont
                  foreground: *cyan
                  on-click: /usr/bin/bash -c "fuzzel-run"
              - string:
                  text: 
                  font: *sfont
                  foreground: *cyan
                  on-click: /usr/bin/bash -c "footclient nnn"
              - string:
                  text: 
                  font: *sfont
                  foreground: *cyan
                  on-click: /usr/bin/bash -c "footclient nvim"
              - string: {<<: *separator}

    - river:
        anchors:
          - string: &default {text: '{id}'}
          - focused: &focused
              foreground: *base07
              deco: {underline: {size: 2, color: *pink}}
          - invisible: &invisible {foreground: *base05}
        content:
          - map:
              tag: occupied
              values:
                false: {empty: {}}
                true:
                  map:
                    tag: state
                    values:
                      invisible:
                        string: {margin: 8, <<: [*default, *invisible]}
                      focused:
                        string: {margin: 8, <<: [*default, *focused]}

  # [ Center ]
  center:
    - river:
        title:
          - string:
              text: '[ '
              foreground: *base05
          - string:
              text: '{title}'
              foreground: *base05
              max: 80
          - string:
              text: ' ]'
              foreground: *base05
        content: {string: {text: ''}}

  # [ Right ]
  right:
    - script:
        path: /home/novakane/.config/yambar/modules/cpu.sh
        args: [1]
        content:
          list:
            spacing: 3
            items:
              - string:
                  text: 
                  font: *sfont
              - string:
                  text: '{cpu}'

    - script:
        path: /home/novakane/.config/yambar/modules/pacman.sh
        args: []
        content:
          map:
            tag: pkg
            default:
              list:
                spacing: 3
                items:
                  - string:
                      text: 
                      font: *sfont
                  - string:
                      text: '{pkg}'
                      font: *myfont
            values:
              0:
                string:
                  text: no updates
                  font: *sfont

    - alsa:
        card: default
        mixer: Master
        content:
          map:
            tag: muted
            values:
              true:
                list:
                  spacing: 3
                  items:
                    - string:
                        text: 
                        font: *sfont
                        foreground: *pink
                    - string:
                        text: '{volume}'
                        foreground: *pink
              false:
                list:
                  spacing: 3
                  items:
                    - ramp:
                        tag: volume
                        items:
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                    - string:
                        text: '{volume}'
                        font: *myfont

    - battery:
        name: BAT1
        poll-interval: 30
        content:
          map:
            tag: state
            values:
              discharging:
                list:
                  spacing: 3
                  items:
                    - ramp:
                        tag: capacity
                        items:
                          - string:
                              text: 
                              font: *sfont
                              foreground: *pink
                          - string:
                              text: 
                              font: *sfont
                              foreground: *pink
                          - string:
                              text: 
                              font: *sfont
                              foreground: *yellow
                          - string:
                              text: 
                              font: *sfont
                              foreground: *yellow
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                          - string:
                              text: 
                              font: *sfont
                              foreground: *green
                    - string:
                        text: '{capacity}%'
                        font: *myfont
              charging:
                list:
                  spacing: 3
                  items:
                    - string:
                        text: 
                        foreground: *blue
                        font: *sfont
                    - string:
                        text: '{capacity}%'
                        font: *myfont
              full:
                list:
                  spacing: 3
                  items:
                    - string:
                        text: 
                        foreground: *green
                        font: *sfont
                    - string:
                        text: '{capacity}%'
                        font: *myfont

    - network:
        name: wlan0
        content:
          map:
            tag: state
            default:
              string:
                text: 直
                font: *sfont
            values:
              down:
                string:
                  text: 睊
                  font: *sfont
                  foreground: *pink
              up:
                map:
                  tag: ipv4
                  default:
                    string:
                      text: 直
                      font: *sfont
                  values:
                    '':
                      string:
                        text: 直
                        font: *sfont

    - clock:
        time-format: '%H:%M'
        date-format: '%a %d/%m'
        content:
          list:
            spacing: 5
            items:
              - string: {<<: *separator}
              - string:
                  text: '{date}'
                  font: *sfont
              - string: {<<: *separator}
              - string:
                  margin: 10
                  text: '{time}'
                  foreground: *yellow
                  deco: {underline: {size: 2, color: *yellow}}
