- defaults:
    link:
        relink: true
    create: true

- clean:
    '~':
        force: true
    '~/.config':
        recursive: true
    '~/.local':
        recursive: true

# - shell:
#     - [git submodule update --init --remote, Installing submodules]

