#!/usr/bin/env zsh

# [ Aize Colors ]

declare -r base00='#29223a'
declare -r base01='#3e3350'
declare -r base02='#534666'
declare -r base03='#6b5c7c'
declare -r base04='#837593'
declare -r base05='#9d8fa9'
declare -r base06='#b7acbf'
declare -r base07='#d2ccd6'

declare -r red='#f63d81'
declare -r pink='#fc65b0'
declare -r orange='#f5939c'
declare -r yellow='#e8ec77'
declare -r green='#2dcbb0'
declare -r blue='#57bbf4'
declare -r magenta='#a89bee'
declare -r cyan='#4db9c8'

