#!/usr/bin/env bash
#
# Search files with fd
#
# REQUIREMENTS: fd

. "$(dirname "$0")"/.nnn-plugin-helper

printf "pattern: "
read -r pattern

if [[ -n "${pattern}" ]]; then
	printf "%s" "+l" >"$NNN_PIPE"
	eval "fd -HI ${pattern} -0" >"$NNN_PIPE"
fi
