#!/usr/bin/env sh

# Scan file with ClamAV

scan () {
  if command -v clamscan >/dev/null 2>&1; then
    if [ -d "$1" ]; then
      clamscan --recursive "$1"
    else
      clamscan "$1"
    fi
  fi
}

