#!/usr/bin/env bash
#
# Environement global user


# [ User bin ]
if [[ -d "$HOME"/.local/bin ]]; then
    _prepend_path "$HOME"/.local/bin
    _prepend_path "$HOME"/.local/bin/app
    _prepend_path "$HOME"/.local/bin/colors
fi

# [ User lib ]
[[ -z "$LIB_HOME" ]] && export LIB_HOME="$HOME"/.local/lib

