#!/usr/bin/env bash
#
# Environement for programming lib


# [ Dircolors ]
if [[ -r "${_shell_plugins_dir}"/dircolors ]]; then
  eval "$(dircolors -b "${_shell_plugins_dir}"/dircolors)"
fi

# [ Starship ]
if [[ -r "${_shell_plugins_dir}"/starship.toml ]]; then
    export STARSHIP_CONFIG="${_shell_plugins_dir}"/starship.toml
fi

# [ Zoxide ]
_is_command zoxide && { export _ZO_ECHO=1; export _ZO_RESOLVE_SYMLINKS=1; }


# [ Personnal custom ]
# Colors
[[ -d "${_shell_plugins_dir}"/colors ]] && . "${_shell_plugins_dir}"/colors/kosmikoa

# Configure shell to emit the OSC 7 escape sequence
[[ -r "${_shell_plugins_dir}"/osc7 ]] && . "${_shell_plugins_dir}"/osc7

