#!/usr/bin/env bash
#
# Environement for programming lib


# [ Fzf ]
if [[ -d "${_fzf_dir}" ]]; then
  _append_path "${_fzf_dir}"/bin

  export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden -E .git --color=always'
  # Uses tree command to show the entries of the directory
  export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

  _gen_fzf_default_opts() {
    export FZF_DEFAULT_OPTS="
    --color=bg+:${base00},bg:${base00},spinner:${pink},hl:${green}
    --color=fg:${base05},header:${pink},info:${pink},pointer:${yellow}
    --color=marker:${blue},fg+:${base07},prompt:${pink},hl+:${yellow}
    --height 50% --reverse --margin 2% --cycle --multi --ansi
    "
  }

  _gen_fzf_default_opts

  # Use fd instead of the default find
  _fzf_compgen_path() { fd --hidden --follow --exclude ".git" . "$1"; }

  # Use fd to generate the list for directory completion
  _fzf_compgen_dir() { fd --type d --hidden --follow --exclude ".git" . "$1"; }

fi

# [ Less ]
# Set the default Less options.
if _is_command less; then
    export LESS='-g -i -M -R -S -w -z-4'
    export LESSHISTFILE="$XGG_CACHE_HOME"/less

    # Colors
    export LESS_TERMCAP_md=$'\e[1;31m'
    export LESS_TERMCAP_me=$'\e[0m'
    export LESS_TERMCAP_se=$'\e[0m'
    export LESS_TERMCAP_so=$'\e[1;40;36m'
    export LESS_TERMCAP_ue=$'\e[0m'
    export LESS_TERMCAP_us=$'\e[1;33m'
fi

# [ Neovim ]
export DIFFPROG="nvim -d" # Use neovim instead of vim for pacdiff

# Give a name to nvim server to start with neovim-remote
_is_command nvr && export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim

# [ Notmuch ]
_is_command notmuch && export NOTMUCH_CONFIG="$XDG_CONFIG_HOME"/notmuch/config

# [ Nnn ]
if _is_command nnn; then
    export NNN_OPTS="ceEH"
    export NNN_COLORS='3415'
    export NNN_FCOLORS='070704030f05060808010301'
    export NNN_TRASH=1
    export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"
    export NNN_SEL='/tmp/.sel'
    export NNN_FIFO='/tmp/nnn.fifo'
    export NNN_BMS="\
c:~/.config;\
n:~/.config/nvim;\
z:~/.config/zsh;\
a:~/.config/awesome;\
s:~/.config/shell;\
i:~/img;\
g:~/dev;\
b:~/.local/share/bld;\
e:~/.local/share/notes;\
l:~/.local;\
d:~/.local/share/dotfiles;"
    export NNN_PLUG="\
f:fuzzy;\
i:imgview;\
o:open;\
c:cmx;\
e:exec;\
n:nvr;\
a:_unar ${nnn}*"
fi

# [ Pass ]
_is_command pass && export PASSWORD_STORE_DIR="$HOME"/.private/pass

# [ Ripgrep ]
_is_command rg && export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME"/ripgrep/rc


# [ Misc ]
# Cleanup $HOME dir
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export PARALLEL_HOME="$XDG_CACHE_HOME"/parallel
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

