#!/usr/bin/env bash
#
# [ Aize colors ]


declare base00 base01 base02 base03 base04 base05 base06 base07
declare red pink orange yellow green blue magenta cyan

# [ Colors ]
base00='#29223a'
base01='#3e3350'
base02='#534666'
base03='#6b5c7c'
base04='#837593'
base05='#9d8fa9'
base06='#b7acbf'
base07='#d2ccd6'

red='#f63d81'
pink='#fc65b0'
orange='#f5939c'
yellow='#e8ec77'
green='#2dcbb0'
blue='#57bbf4'
magenta='#a89bee'
cyan='#4db9c8'

