#!/usr/bin/env bash
#
# [ Argi colors ]


declare base00 base01 base06 base07
declare red blue

# [ Colors ]
base07='#252524'
base06='#39404a'
base01='#dfe1e3'
base00='#f1f1f0'

red='#692652'
blue='#1f4357'

