#!/usr/bin/env bash
#
# Display dwl tags in waybar


declare -a tags
tags=(" 1 " " 2 " " 3 " " 4 " " 5 " " 6 " " 7 " " 8 " " 9 ")
fname=/tmp/dwltags-"$WAYLAND_DISPLAY"

# Display tags at launch
_startup() {
  printf -- '%s%s%s%s%s%s%s%s%s\n' "${tags[*]}"
}

main() {
  _startup "$@"

  while true
  do
    # Make sure the file exists
    while [ ! -f "${fname}" ]
    do
      inotifywait -qqe create "$(dirname "${fname}")"
    done;

    # Wait for dwl to close it after writing
    inotifywait -qqe close_write "${fname}"

    local titleline tagline title taginfo isactive ctags mtags layout
    red="\e[0;91m"
    reset="\e[0m"
    titleline="$1"
    tagline=$((titleline+1))
    title=$(sed "${titleline}!d" "${fname}")
    taginfo=$(sed "${tagline}!d" "${fname}")
    isactive=$(printf -- '%s\n' "${taginfo}" | cut -d ' ' -f 1)
    ctags=$(printf -- '%s\n' "${taginfo}" | cut -d ' ' -f 2)
    mtags=$(printf -- '%s\n' "${taginfo}" | cut -d ' ' -f 3)
    layout=$(printf -- '%s\n' "${taginfo}" | cut -d ' ' -f 4-)

    for i in {0..8};
    do
      mask=$((1<<i))

      if (( "${ctags}" & mask ));
      then
        n="$((i+1))."
      else
        n="$((i+1))"
      fi

      if (( "${mtags}" & mask ));
      then
        echo -n "[ ${n} ]"
      else
        echo -n " ${n} "
      fi
    done

    # printf -- ' %s %s \n' "${layout}" "${title}"
    printf -- ' %s \n' "${layout}"

  done

  unset -v titleline tagline title taginfo isactive ctags mtags layout
  unset -f _startup
}

main "$@"

