#!/usr/bin/env bash
#
# [ Kosmikoa theme ]


declare base00 base01 base02 base03 base04 base05 base06 base07
declare red pink orange yellow green blue magenta cyan

# [ Colors ]
base00='#252524'
base01='#464645'
base02='#59566d'
base03='#6b6883'
base04='#7e7b97'
base05='#bfbdcb'
base06='#d4d3dc'
base07='#f1f1f0'

red='#842a4d'
pink='#fc65b0'
orange='#f08c89'
yellow='#e8ec77'
green='#62e89e'
blue='#2a4d84'
magenta='#be8fde'
cyan='#00cfd0'


# [ Theme ]
riverctl background-color "${base07}"
riverctl border-color-focused "${red}"
riverctl border-color-unfocused "${base00}"
riverctl border-width 2
riverctl xcursor-theme Adwaita

# Set opacity and fade effect
# riverctl opacity 1.0 0.75 0.0 0.1 20


unset -v base00 base01 base02 base03 base04 base05 base06 base07
unset -v red pink orange yellow green blue magenta cyan

