#!/usr/bin/env bash
#
# [ Kosmikoa theme ]


declare light00 light01 light02 dark00 dark01 dark02
declare red blue

# [ Colors ]
light00='#f1f1f0'
light01='#dfe1e3'
light02='#d1d3d6'

dark00='#252524'
dark01='#39404a'
dark02='#656d78'

red='#692652'
blue='#1f4357'


# [ Theme ]
riverctl background-color "${light00}"
riverctl border-color-focused "${red}"
riverctl border-color-unfocused "${dark00}"
riverctl border-width 2
riverctl xcursor-theme Adwaita

# Set opacity and fade effect
# riverctl opacity 1.0 0.75 0.0 0.1 20


unset -v light00 light01 light02 dark00 dark01 dark02
unset -v red blue

