#!/usr/bin/env bash
#
# [ Kosmikoa theme ]


declare base00 base01 base02 base03 base04 base05 base06 base07
declare red pink orange yellow green blue magenta cyan

# [ Colors ]
base00='#23222b'
base01='#474557'
base02='#59566d'
base03='#6b6883'
base04='#7e7b97'
base05='#bfbdcb'
base06='#d4d3dc'
base07='#eae9ee'

red='#ec5382'
pink='#fc65b0'
orange='#f08c89'
yellow='#e8ec77'
green='#62e89e'
blue='#57bbf4'
magenta='#be8fde'
cyan='#00cfd0'


# [ Theme ]
riverctl background-color "${base00}"
riverctl border-color-focused "${blue}"
riverctl border-color-unfocused "${base01}"
riverctl border-width 2
riverctl set-option outer_padding
riverctl set-option view_padding
riverctl set-option -focused-output outer_padding 0
riverctl set-option -focused-output view_padding 3
riverctl xcursor-theme capitaine-cursors 24

# Set opacity and fade effect
# riverctl opacity 1.0 0.75 0.0 0.1 20


unset -v base00 base01 base02 base03 base04 base05 base06 base07
unset -v red pink orange yellow green blue magenta cyan

