#!/usr/bin/env bash
#
# Open apps
# note: xdg-open has a bug with .desktop files, so we cant use that
#     - Requirements: fzf


# @FIXME: Doesn't work anymore???
fapp() {
  local selected

  selected="$(find /usr/share/applications -type f -printf '%P\n' | fzf -e)"

  nohup "$(grep '^Exec' /usr/share/applications/"${selected}" \
    | tail -1 \
    | sed 's/^Exec=//' \
    | sed 's/%.//')" \
    >/dev/null 2>&1&
}

