#!/usr/bin/env bash
#
# cd to selected directory
#     - Requirements: fzf


fcd() {
  local dir

  dir=$(find "${1:-.}" -path '*/\.*' -prune -o -type d -print 2> /dev/null \
                  | fzf +m) &&

  cd "${dir}" || exit
}

