#!/usr/bin/env bash
#
# Open images with sxiv or imv
#     - Requirements: fzf, fd, sxiv/imv


# Error message in STDERR
_err() {
  printf -- '%s\n' "[$(date +'%Y-%m-%d %H:%M:%S')]: $*" >&2
}

fimg() {
  emulate -L bash
  local files

  if hash imv &> /dev/null; then
    mapfile -t files < <(fd -p -e jpg -e png . \
      | fzf --query="$1" --multi --select-1 --exit-0)

    [[ -n "${files[*]}" ]] && imv "${files[@]}"

  elif hash sxiv &> /dev/null; then
    mapfile -t files < <(fd -p -e jpg -e png . \
      | fzf --query="$1" --multi --select-1 --exit-0)

    [[ -n "${files[*]}" ]] && sxiv "${files[@]}"

  else
    _err "You need Sxiv or Imv"
    exit 1
  fi

  unset -f _err
}

