#!/usr/bin/env bash
#
# Kill processes - list only the ones you can kill. 
#     - Requirements: fzf


fkill() {
  local pid 

  if [ "$UID" != "0" ]; then
    pid=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
  else
    pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
  fi  

  if [ "x${pid}" != "x" ]
  then
    printf -- '%s\n' "${pid}" | xargs kill -"${1:-9}"
  fi
}

