#!/usr/bin/env bash
#
# Search installed pkg
#     - Requirements: fzf


# fpkg() { pacman -Qe | fzf -e; }
fpkg() {
  pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
}

