#!/usr/bin/env bash
#
# Fuzzy grep via rg and open in vim with line number
#     - Requirements: fzf, rg, neovim


frg() {
  local file line

  if [[ $# -eq 0 ]]; then
    printf -- '%s\n' \
      "[$(date +'%Y-%m-%d %H:%M:%S')]: Require at least one argument" >&2
  fi

  read -r file line <<<"$(rg --no-heading --line-number 2> /dev/null "$@" \
    | fzf -0 -1 \
    | awk -F: '{print $1, $2}')"

  [[ -n "${file}" ]] && nvim "${file}" +"${line}"
}

