#!/usr/bin/env bash
#
# Open a file in neovim at given line


nl() {
  local file line

  if [[ $# -ne 2 ]]; then
    printf -- '%s\n' \
      "[$(date +'%Y-%m-%d %H:%M:%S')]: Require two arguments" >&2
  fi

  file="$1"
  line="$2"

  [[ -n "${file}" ]] && ${EDITOR:-nvim} "${file}" +"${line}"
}
