#!/usr/bin/env bash
#
# [ ALIASES ]


# [ xbps ]
alias xi='sudo xbps-install'
alias xq='xbps-query -Rs'
alias xu='sudo xbps-install -Su'
alias xr='sudo xbps-remove -Ro'
alias xclean='sudo xbps-remove -Oo'
alias xinfo='xbps-query'

# [ Exa ]
alias exa='exa --group-directories-first --icons'
alias ea='exa -lah --group-directories-first --git --icons'
alias et='exa -lah -TL2 --group-directories-first --git --icons'

# [ Git ]
alias g='git status'
alias ga='git add'
alias gb='git branch'
alias gc='git clone'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gl='git log'
alias gp='git push'
alias gr='git rebase'
alias gs='git switch'
alias gu='git pull'

# [ Neovim ]
alias sedit='sudo -E nvim'
alias enote='cd "$XDG_DATA_HOME"/notes && nvim'
alias qnote='nvim "$XDG_DATA_HOME"/notes/quick.md'
alias e='nvim'

# [ Nnn ]
alias N='sudo -E nnn'

# [ Ripgrep]
alias rgi='rg --no-ignore'

# [ Runit ]
alias renable='sudo ln -s etc/sv/"$1" /var/service'
alias rdisable='sudo rm /var/service/"$1"'
alias rstatus='sudo sv s /var/service/"$@"'
alias rustatus='sv s "$SVDIR"/"$@"'

# [ Trash-cli ]
alias del='trash-put'
alias restore='trash-restore'

# [ Wireguard ]
alias wgup='wg-quick up'
alias wgdown='wg-quick down'

# [ Lang ]
alias z7='zig-0.7.1v'
alias cargou='cargo-install-update install-update'

# [ Files ]
alias ls='ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll='ls -l --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias la='ls -la --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias grep='grep --color=always -d skip'
alias cp='cp -i'
alias df='df -h'
alias free='free -m'
alias cmx='chmod 774'
alias perm='stat -c "%A %a %n"'

# [ Misc ]
alias :q='exit'
alias wget='wget --hsts-file="$XDG_CACHE_HOME"/wget-hsts'
alias mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'
alias myip='curl ifconfig.co/json'

