#!/usr/bin/env bash
#
# Autostart prpgram at river launch


riverctl spawn 'swaybg -i ~/img/wal/tonton_revolver_john_wick_01.jpg >/dev/null 2>&1'
riverctl spawn 'foot --server >/dev/null 2>&1'
riverctl spawn 'fnott >/dev/null 2>&1'
riverctl spawn 'yambar >/dev/null 2>&1'
