#!/usr/bin/env bash
#
# [ River Config ]


declare river_dir
declare -a azerty tags main_fctr main_amt

# Workaround for azerty keyboard
azerty=( ampersand eacute quotedbl apostrophe parenleft minus egrave underscore ccedilla )
tags=( 1 2 4 8 16 32 64 128 256 )
main_fctr=( 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 )
main_amt=( 1 2 3 4 5 6 7 8 9 )

river_dir="$XDG_CONFIG_HOME"/river

source "${river_dir}"/autostart


# ------------------------------------------------
# [ Options ]
# ------------------------------------------------

riverctl set-repeat 50 300      # Set repeat rate
# Set the layout on startup
# riverctl layout rivertile tile-left
riverctl spawn rivertile
riverctl set-option -focused-output layout tile-left
riverctl attach-mode bottom
riverctl focus-follows-cursor normal

source "${river_dir}"/themes/kosmikoa

# Set app-ids of views which should float
riverctl float-filter-add "float"
riverctl float-filter-add "popup"
riverctl float-filter-add "imv"
riverctl float-filter-add "mpv"

# Set app-ids of views which should use client side decorations
# riverctl csd-filter-add "gedit"
# riverctl csd-filter-add "firefox"


# ------------------------------------------------
# [ Keybind ]
# ------------------------------------------------

mod="Mod4" # Logo key
term=footclient
browser=firefox

# [ App ]
riverctl map normal $mod Return spawn $term
riverctl map normal Control+Shift Return spawn $term
riverctl map normal $mod D spawn dmenu-run
riverctl map normal $mod B spawn $browser
riverctl map normal $mod O spawn fuzzel-run
riverctl map normal $mod S spawn foot-float


# Mod+E to exit river
riverctl map normal $mod+Shift E exit


# [ Views ]
# Mod+Q to close the focused view
riverctl map normal $mod Q close

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod+Shift Return zoom

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view


# [ Layouts ]
riverctl map normal $mod Space toggle-float  # Mod+Space to toggle float
riverctl map normal $mod F toggle-fullscreen # Mod+F to toggle fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up spawn riverctl set-option -focused-output layout tile-up
riverctl map normal $mod Right spawn riverctl set-option -focused-output layout tile-right
riverctl map normal $mod Down spawn riverctl set-option -focused-output layout tile-down
riverctl map normal $mod Left spawn riverctl set-option -focused-output layout tile-left

for i in {0..9}; do
  # Decrease/increase the main factor
  # If using rivertile(1) this determines the width of the main stack.
  riverctl map normal $mod+Mod1 "${azerty[i]}" spawn riverctl set-option \
    -focused-output main_factor "${main_fctr[i]}"
  # Increment/decrement the number of main views in the layout
  riverctl map normal $mod+Mod1+Shift "${azerty[i]}" spawn riverctl set-option \
    -focused-output main_amount "${main_amt[i]}"
done

# [ Tags ]
for i in {0..9}; do
  riverctl map normal $mod "${azerty[i]}" set-focused-tags "${tags[i]}"
  riverctl map normal $mod+Shift "${azerty[i]}" set-view-tags "${tags[i]}"
  riverctl map normal $mod+Control "${azerty[i]}" toggle-focused-tags "${tags[i]}"
  riverctl map normal $mod+Shift+Control "${azerty[i]}" toggle-view-tags "${tags[i]}"
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
# all_tags=$(((1 << 32) - 1))
# riverctl map normal $mod agrave set-focused-tags $all_tags
# riverctl map normal $mod+Shift agrave set-view-tags $all_tags
tags1to9=$(((1 << 9) - 1))
riverctl map normal $mod agrave set-focused-tags $tags1to9
riverctl map normal $mod+Shift agrave set-view-tags $tags1to9


# [ Passthrough ]
# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal


# [ Special keys ]
# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
	# Volume
	riverctl map $mode None XF86AudioRaiseVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +5%
	riverctl map $mode None XF86AudioLowerVolume spawn pactl set-sink-volume @DEFAULT_SINK@ -5%
	riverctl map $mode None XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle

	# Brighness
	riverctl map $mode None XF86MonBrightnessUp spawn brightnessctl set 5%-
	riverctl map $mode None XF86MonBrightnessDown spawn brightnessctl set +5%

done

# Screenshot
riverctl map normal $mod Print spawn 'snap -f'
riverctl map normal $mod+Shift Print spawn 'snap -s'


unset -v river_dir
unset -v azerty tags main_fctr main_amt
